### ISSUE TITLE
Refresh Optimizations

### ISSUE THREAD

**Issue by numtel** [FocusSchoolSoftware/pg-live-query#2]
Discussion of plans to optimize the refreshing of result sets
- For simple queries that generate [updatable views](http://www.postgresql.org/docs/9.4/static/sql-createview.html#SQL-CREATEVIEW-UPDATABLE-VIEWS), push serialized changed rows in the trigger's `NOTIFY` payload then verify if they match the original query using a simple CTE with the specified `WHERE` clause appended.
- Re-introduce manual triggers

Both of these options require putting the serialized changed row data in the `NOTIFY` payload.

**Comment by numtel** [comment]
Placing the row data into the `NOTIFY` payload [has been implemented](https://github.com/FocusSchoolSoftware/pg-live-query/commit/ca720df53f4b864802cd755695088723b34f1fbc) as well as manual triggers. 

Manual triggers have very high response times even though fewer queries are being performed. More analysis is needed.

Still `TODO`: implement pagination on payload to 8000 bytes

In order to determine if a query's corresponding view is updatable, [getQueryTables is now getQueryDetails](https://github.com/FocusSchoolSoftware/pg-live-query/commit/9e26ec3a6fb29c497411c28b9bdcd0ba158f7f9e).

Next for simple queries: each row from the payload must be cached until the next refresh occurs then tested if matching result set using CTE with `json_populate_recordset` function call against query with `WHERE` clause of the original query.

**Comment by numtel** [comment]
While [working towards getting the simple queries operational](https://github.com/FocusSchoolSoftware/pg-live-query/commit/7551ae27050ce796ca4eec757de2c558604d8297), I was trying to figure out how to extract the `WHERE` clause from the `SELECT` statement and came across the [`sql-parser` NPM package](https://github.com/forward/sql-parser).

With this package, it seems like we should not have to run any queries to get the diff and may even be able to recreate the sort order in Javascript.

**Comment by numtel** [comment]
Okay, I've [prepared the LIMIT/OFFSET features that we may need in the sql-parser package](https://github.com/forward/sql-parser/pull/8).

Next, there must be a system for matching rows from the `NOTIFY` payloads to a parsed query `WHERE` clause. The simple `ORDER BY`, `LIMIT` and `OFFSET` clauses will be transformed into their respective Javascript Array operations and finally the selected columns must be picked from the row objects.

**Comment by numtel** [comment]
[Row matcher module has been implemented](https://github.com/FocusSchoolSoftware/pg-live-query/blob/35c00e02f65445df3a4063ad249d38d3a5707d89/test/matchRowsToParsedQuery.es6)

**Comment by numtel** [comment]
[Progress made on implementing the row matching module](https://github.com/FocusSchoolSoftware/pg-live-query/commit/6210463cbff2e18bf176bbd9040547d427ccb3b8)

The next step is translating `ORDER BY` and `LIMIT` into Javascript analogs. `OFFSET` is not compatible with this approach as there is no way of knowing about rows that exist outside of the offset.

This limitation also effects `DELETE` operations. In queries with a `LIMIT` clause and the last-known result set length is at the limit, when a row is deleted, the query must be re-executed in order to obtain the row that may possibly fill the position of the deleted row. Definitely not a show-stopper but very important to work around.

In cases where a simple query is shown to be incompatible with this method it will automatically fall back to full-refreshing style for all future updates. (e.g. error thrown in `matchRowsToParsedQuery` module, contains `OFFSET` clause).

Also, all rows must be unique (e.g. include a primary key).

**Comment by nothingisdead** [comment]
Looking good! I see what you mean about the DELETE/LIMIT and OFFSET
limitations. I wonder how the mongo driver works with the $skip operator. I
remember that it wasn't very efficient, but I think they improved it
recently.

I was thinking about a way to make more efficient use of the memory by
combining data sets that have the same query but different parameters. We
would need to have a reference counter like before, but it would store a
hash of the parameters as the reference, e.g.

cache = [
   {
       row: {...}, // row data
       refs: [hash1, hash2, etc.]
   }

];

...where hash1 and hash2 are the hashes of parameter sets. This would
almost halve the memory usage for the following 2 queries (an extreme
example):

select \* from students where id < 100;
select \* from students where id < 101;

What do you think?

Bob

**Comment by numtel** [comment]
A [load test for the simple query style](https://github.com/FocusSchoolSoftware/pg-live-query/commit/af34d79af97744a844f08a70b8d1fa46eecd248f) is now committed.

With the same operation rates as the default test (90 insert/90 update), 8800 of 10324 responses are dropped after 73 seconds. The few that do come through are not quick either. There must be some bugs in the implementation.

Also, still `TODO`: pick columns from table data that match query `SELECT ... FROM`, currently only supports `SELECT *`

---

About the row cache: the memory usage and response times will need to be thoroughly tested.

In the `rowcache` branch, I do not understand why the index of the row is stored as a property of the `Row` object. I think you'd be better off storing an array of hashes for each result set then keep a simpler hashmap containing the row data keyed by hash.

Instead of a separate class for the `Row`, a property on the `LiveSQL` class named `rowCache` would contain the row data. Ideally, this would be a [`Map` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), which Babel polyfills, I don't know if there's a performance gain without the native support though. The `LiveSQL.selectBuffer[].data` collection can be updated to contain the array of hashes, and probably should be renamed to something like `hashes` to be more descriptive.

``` javascript
// Inside a LiveSQL method, mapping hashes to rows becomes:
currentData = queryBuffer.hashes.map((hash, index) => {
  let row = this.rowCache[hash]
  row._index = index
  return row
})
```

**Comment by nothingisdead** [comment]
Hey,

The index is stored as a property of the Row object so that I can reuse the
same data with different indexes by creating a separate instance for each
row (assuming the instance takes up less memory than the row data itself,
which might not be correct). Your approach would work too, and probably
much better :) I'll hopefully work on that today unless I am pulled away.

Strange that the simple queries aren't very fast and are dropping
responses. I wonder if the notifications aren't as reliable as we think?

Thanks,
Bob

**Comment by numtel** [comment]
I identified and [removed an extra loop in `getDiffFromSupplied`](https://github.com/FocusSchoolSoftware/pg-live-query/commit/167046ae06a62b0574e0f39fefb1b95e67e26654) which greatly reduces the execution time. The response time performance is not quite what I had hoped for. The memory usage is much lower but the whole thing crashes much faster than before: within about 7 minutes, responses stop vs. ~25 minutes with the complex query.

~7 minute duration:

![simple-query-end-to-end-7mins](https://cloud.githubusercontent.com/assets/518698/6747653/93e53ea4-ce99-11e4-9722-05766d1d9b19.png)

You can see the response times spiking in this ~1 minute duration graph:

![simple-query-response-times-1min](https://cloud.githubusercontent.com/assets/518698/6747660/b8fcba5a-ce99-11e4-8499-d6495f58dddf.png)

I wonder if these spikes represent a long event loop block since there is no longer an asynchronous action during refresh. I added `await nextTick` in a few places throughout `getDiffFromSupplied` but it does not seem to have fixed the problem.

There is also now a [unit load test for `getDiffFromSupplied`](https://github.com/FocusSchoolSoftware/pg-live-query/commit/36f23ac4203564f5d1149252d8cffc7df6fe2e3c). The memory usage does not seem to leak but the same spiking pattern emerges (albeit on a longer timescale).

![getdifffromsupplied-6mins](https://cloud.githubusercontent.com/assets/518698/6747667/dc56da6c-ce99-11e4-962a-e04cd565d68e.png)
