### ISSUE TITLE
Can this work on redshift?

### ISSUE THREAD

**Issue by Tarang** [FocusSchoolSoftware/pg-live-query#3]
This question may carry some distance.

Can this module be used with AWS Redshift? It's based off PostgreSQL so theoretically it should work

**Comment by numtel** [comment]
This will not work with Redshift as it was [based on Postgres 8.0.2](http://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html).

The JSON functions (`json_agg`) required for this package were not implemented until 9.3.
